changelog:
  categories:
    - title: Breaking changes
      labels: [breaking-change]
    - title: Security
      labels: [security]
    - title: Features
      labels: [enhancement]
    - title: Bug fixes
      labels: [bug]
    - title: Documentation
      labels: [documentation]
  exclude:
    labels: [skip-changelog]
    authors: [github-actions]
